### ISSUE TITLE
Are default examples broken?

### ISSUE THREAD

**Issue by beeradmoore** [gabrielkaputa/bitly#3]
When I try use the examples in the readme,
`$bitly = \GabrielKaputa\Bitly::withGenericAccessToken(BITLY_ACCESS_TOKEN);`
I get this error.

> PHP Fatal error:  Class 'GabrielKaputa\\Bitly'

But when I write the code as,
`$bitly = \GabrielKaputa\Bitly\Bitly::withGenericAccessToken(BITLY_ACCESS_TOKEN);`
it works.

Did something get updated but the readme didn't?

**Comment by gabrielkaputa** [comment]
hi, nothing changed, should work as in reamde. could you provide some code that would reproduce your issue?
